// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuN_td8HY11bfQZvusjNcqM524nZTZskU',
    appId: '1:769051508866:web:5ab1742b4c167a4412749b',
    messagingSenderId: '769051508866',
    projectId: 'irl-game-7ac37',
    authDomain: 'irl-game-7ac37.firebaseapp.com',
    storageBucket: 'irl-game-7ac37.appspot.com',
    measurementId: 'G-D5WQF7JQ7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1pL5cUWMl9IBLxi3LWPFsSdqc7c_WMf0',
    appId: '1:769051508866:android:6e10336458ea046312749b',
    messagingSenderId: '769051508866',
    projectId: 'irl-game-7ac37',
    storageBucket: 'irl-game-7ac37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeL1bd-0FzPEAV_3SOVpOgofvuaVUBsQM',
    appId: '1:769051508866:ios:94cb091a63c1ecdb12749b',
    messagingSenderId: '769051508866',
    projectId: 'irl-game-7ac37',
    storageBucket: 'irl-game-7ac37.appspot.com',
    androidClientId: '769051508866-nl7ikbc5ltegkmrhgu86216oeehlmqa9.apps.googleusercontent.com',
    iosClientId: '769051508866-ve0obh26hma91fjf969p76vbbr558d7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeL1bd-0FzPEAV_3SOVpOgofvuaVUBsQM',
    appId: '1:769051508866:ios:94cb091a63c1ecdb12749b',
    messagingSenderId: '769051508866',
    projectId: 'irl-game-7ac37',
    storageBucket: 'irl-game-7ac37.appspot.com',
    androidClientId: '769051508866-nl7ikbc5ltegkmrhgu86216oeehlmqa9.apps.googleusercontent.com',
    iosClientId: '769051508866-ve0obh26hma91fjf969p76vbbr558d7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuN_td8HY11bfQZvusjNcqM524nZTZskU',
    appId: '1:769051508866:web:95352bb2cfde12f012749b',
    messagingSenderId: '769051508866',
    projectId: 'irl-game-7ac37',
    authDomain: 'irl-game-7ac37.firebaseapp.com',
    storageBucket: 'irl-game-7ac37.appspot.com',
    measurementId: 'G-DWW89Y0SBL',
  );

}